name: release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  validate:
    name: Validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    runs-on: "ubuntu-latest"
    env:
      CI: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.12

      - name: Install dependencies
        run: bun install

      - name: Check formatting and typing
        run: bun run check

      - name: Run tests
        run: bun run test

      - name: Run build
        run: bun run build

  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: validate
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.12

      - name: Install dependencies
        run: bun install

      - name: Run build
        run: bun run build

      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          title: "Release new version"
          commit: "update version"
          publish: bun run publish:ci
          version: bun run publish:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
